repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: check-yaml
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: format-backend
        name: Format python codes
        entry: bash -c 'cd ./backend/ && poetry run poe format'
        language: python
        files: ^backend/

      - id: prettier
        name: Run prettier
        entry: bash -c 'cd ./frontend/ && npm run format'
        language: node
        files: ^frontend/
